### PR TITLE
removing video title tooltip on mouse hover + optimize images

### PR DESCRIPTION
**Pull request by WAZAAAAA0**
hide the annoying video title tooltip on mouse hover that often overlaps with videos even while in full screen 
2018-11-08 12_52_44-Michael Jackson - Smooth Criminal (Single Version) HD - Invidious

### CODE REVIEW

**Comment by omarroth** [comment]
The reason it's there is to show video titles on mobile. Example:
on localhost
vs.
on Invidious
Unfortunately there isn't a way that I know of to hide the tooltip without removing the title attribute.

**Comment by omarroth** [comment]
Image changes LGTM.

**Comment by WAZAAAAA0** [comment]
Well screw it then, I've made an userscript
https://greasyfork.org/en/scripts/374225-invidious-tooltip-remover

**Comment by Zero3K** [comment]
Take a look at this for a way to hide the tooltip:

https://stackoverflow.com/questions/3885920/jquery-hide-title-attribute-but-not-remove-it/3886050#3886050

**Comment by omarroth** [comment]
Tooltips should be removed with 0e26e4d. I'd be very happy to merge 3bae0b87c007c38f376fb88f71c415ef2429a84e if you'd like.

**Comment by WAZAAAAA0** [comment]
sounds great

**Comment by omarroth** [comment]
Merged 0f58f872acd374f6ff69c5e00c61bf9fe78e7385.

**Pull request closed without merging**
