### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tmiland**
Add manual commands to Debian and Ubuntu install instructions.

Got a pubkey error on Ubuntu. Added instructions from: https://crystal-lang.org/reference/installation/on_debian_and_ubuntu.html

### CODE REVIEW

**Comment by dimqua** [comment]
Shouldn't this information be moved to the wiki?

**Comment by tmiland** [comment]
> Shouldn't this information be moved to the wiki?

Probably. 

> The wiki is probably a better place for this. `setup.sh` executes `apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54` which should work on any ubuntu and debian.

Wasn't setup.sh removed? It's not in my repos. 🙂

**Comment by Perflyst** [comment]
I am talking about this `setup.sh`: `curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash`

**Comment by tmiland** [comment]
> I am talking about this `setup.sh`: `curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash`

Ah, okay. Well, then, that's the main reason i added the above to the readme, in case someone else would get the same error. 


```
Err:18 https://dist.crystal-lang.org/apt crystal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 09617FD37CC06B54
Reading package lists... Done 
W: GPG error: https://dist.crystal-lang.org/apt crystal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 09617FD37CC06B54
E: The repository 'https://dist.crystal-lang.org/apt crystal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

This is from -->  `setup.sh`: `curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash`

**Comment by omarroth** [comment]
LGTM :+1:

**Pull request merged**
