### PR TITLE
Center video player play button

### PR DESCRIPTION
**Pull request by leonklingele**
Before:

before

After:

after

### CODE REVIEW

**Comment by omarroth** [comment]
As mentioned in #424 I would prefer for this to be added as a preference. If you'd like I can make the appropriate changes to this PR before merging.

**Comment by leonklingele** [comment]
Which of the layouts would you want to use as a default? If you prefer the current style (i.e. button off-center), I'd rather close this PR instead of beginning to clutter the settings with such cosmetic options and provide some *monkey user script instead.

**Comment by omarroth** [comment]
I would prefer to keep the current layout as default for the reasons mentioned [here](https://github.com/omarroth/invidious/pull/424#issuecomment-475457393). If you'd like to implement this as a userscript instead I'd be happy to add it to [Extensions](https://github.com/omarroth/invidious/wiki/Extensions).

**Comment by omarroth** [comment]
Closing in favor of #680.

**Pull request closed without merging**
