### PR TITLE
Display username of currently logged in user

### PR DESCRIPTION
**Pull request by makos**
Closes: #689 

My first PR to this project. I didn't check how it works with Google Login on my localhost Docker instance, but looking through the code a bit it should work just fine. Please correct me if I'm wrong.

### CODE REVIEW

**Comment by makos** [comment]
Why is CI failing? I re-ran the exact steps the test suite is taking and got no error.
```
[makos@laptop-home src]$ ls
total 176K
drwxr-xr-x 4 makos makos 4.0K Feb 13 21:03 invidious
-rw-r--r-- 1 makos makos 172K Feb 13 21:14 invidious.cr
[makos@laptop-home src]$ crystal tool format --check ./* ./invidious/* ./invidious/helpers/*
[makos@laptop-home src]$ echo $?
0
[makos@laptop-home src]$
```

For reference, excerpt from Travis CI:
```
$ crystal tool format --check
formatting './src/invidious/helpers/utils.cr' produced changes
formatting './src/invidious.cr' produced changes
The command "crystal tool format --check" exited with 1.
```

**Comment by leonklingele** [comment]
@makos the latest Crystal 0.33.0 release introduced some changes to the code formatter. Fixed with https://github.com/omarroth/invidious/pull/1031.

**Comment by makos** [comment]
@leonklingele I see. My Arch box is still on 0.32. Will see how I can resolve this.

**Comment by makos** [comment]
Closing this to resolve my git mess. Will reopen with fresh branch.

**Pull request closed without merging**
