### PR TITLE
Centered the "Play" button on the video thumbnail

### PR DESCRIPTION
**Pull request by Leroux47**
If the Play arrow is centered, it will be more accessible and create a more Youtube-like experience.

### CODE REVIEW

**Comment by omarroth** [comment]
There's a comment [here](https://github.com/videojs/video.js/commit/7a8d808b0e547cdc7f0c52790c6c02e4b4f86ff5#diff-85ad37f4d4d62ce0f24ea8a26b95ba09R63) that provides justification for the current appearance of the player:

> By default, the big play button is located in the upper left hand corner so it doesn't cover up the interesting parts of the poster. If you'd prefer to center the big play button, you can add an additional `vjs-big-play-centered` class to your video element.

Since autoplay is currently turned off by default it makes sense to prioritize the poster, and not cover it with the play button.

Video.js also provides a class to do this by default. This PR could be:
```diff
diff --git a/src/invidious/views/components/player.ecr b/src/invidious/views/components/player.ecr
index fef3f72..1280d92 100644
--- a/src/invidious/views/components/player.ecr
+++ b/src/invidious/views/components/player.ecr
@@ -1,5 +1,5 @@
 <video style="outline:none;width:100%" playsinline poster="<%= thumbnail %>" title="<%= HTML.escape(video.title) %>" 
-    id="player" class="video-js"
+    id="player" class="video-js vjs-big-play-centered"
     onmouseenter='this["data-title"]=this["title"];this["title"]=""'
     onmouseleave='this["title"]=this["data-title"];this["data-title"]=""'
     oncontextmenu='this["title"]=this["data-title"]'
```

**Comment by dimqua** [comment]
I think this should only be added as an option.

**Comment by omarroth** [comment]
Since there hasn't been any progress on this PR I'm going to close for now.Anyone who would like to center the play button can use something like
```javascript
document.getElementById('player').setAttribute('class', player.getAttribute('class') + ' vjs-big-play-centered')
```
Or an equivalent rule for uBlock and similar extensions.

**Comment by jg-l** [comment]
Would you accept a PR with a "centered play button" on preferences?

**Comment by jg-l** [comment]
> Since there hasn't been any progress on this PR I'm going to close for now.Anyone who would like to center the play button can use something like
> 
> ```js
> document.getElementById('player').setAttribute('class', player.getAttribute('class') + ' vjs-big-play-centered')
> ```
> 
> Or an equivalent rule for uBlock and similar extensions.

What would it take to get this change on here? The top left button placement is kinda killin' the aesthetics

**Comment by omarroth** [comment]
I would very happily accept a PR with the mentioned option added as a preference.

For a PR I would recommend using:
```erb
id="player" class="video-js <% if preferences.centered_play_button %>vjs-big-play-centered<% end %>"
```

**Comment by omarroth** [comment]
Looks like I missed #424. If you'd like to open a similar PR I can add everything else necessary for it to be merged.

**Comment by jg-l** [comment]
> I would very happily accept a PR with the mentioned option added as a preference.
> 
> For a PR I would recommend using:
> 
> ```
> id="player" class="video-js <% if preferences.centered_play_button %>vjs-big-play-centered<% end %>"
> ```

Got it will make a PR soon

**Comment by omarroth** [comment]
Apologies for not mentioning here, this has been added as part of #680. Available if you select “YouTube” as your preferred player style in preferences.

**Pull request closed without merging**
