### PR TITLE
Update ar.json

### PR DESCRIPTION
**Pull request by EsmailELBoBDev2**

### CODE REVIEW

**Comment by omarroth** [comment]
LGTM, much appreciated! :heart:

**Comment by EsmailELBoBDev2** [comment]
well, can i see examples of  "permalink" & "Premieres `x`" ? to just to know if i did them right  or no

**Comment by omarroth** [comment]
Sure.

"permalink":
image

"Premieres `x`":
image

**Comment by EsmailELBoBDev2** [comment]
i still not understand from "permalink" thing

**Pull request merged**
