### PR TITLE
Rework navbar and update README

### PR DESCRIPTION
**Pull request by FredrikAugust**
Hey. The navbar looked a bit shabby; not aligned with content, used inline css, <center> tags, ++. So I went through some of it and cleaned it up.

If you have any requests for changes, or want some other css cleaned up, just send me a message :)

### CODE REVIEW

**Comment by FredrikAugust** [comment]
2018-07-25-165940_1919x527_scrot

This is how the bar looks when logged in.

**Comment by FredrikAugust** [comment]
The footer is also tweaked slightly, so it will have some space under it when the site has content (sadly can't demonstrate that).

**Comment by omarroth** [comment]
Very nice! I'll have to take a look at this later, thanks!

**Comment by omarroth** [comment]
Looks good on desktop, only issue is that when using dark mode the default color is still white, so it looks like this:
desktop
You may also want to take a look at mobile, on my iDevice it looks like:
iphone.

I'm also curious why you reversed the order of the preferences, sign out, and notifications icons on the right side. 

Otherwise I'd say I'm eager to merge this, it looks quite good and I like the footer.

**Comment by FredrikAugust** [comment]
Thanks for the feedback. 
The dark theme problem is fixed in a whiff, same goes for the ordering. And I'll take a look at the mobile problem as well. 
Should be able to fix it today :) 
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Omar Roth <notifications@github.com> Date: 26/07/2018  4:43 am  (GMT+01:00) To: omarroth/invidious <invidious@noreply.github.com> Cc: Fredrik August Madsen-Malmo <mail.fredrikaugust@gmail.com>, Author <author@noreply.github.com> Subject: Re: [omarroth/invidious] Rework navbar and update README (#38) 
Looks good on desktop, only issue is that when using dark mode the default color is still white, so it looks like this:



You may also want to take a look at mobile, on my iDevice it looks like:

.
I'm also curious why you reversed the order of the preferences, sign out, and notifications icons on the right side.
Otherwise I'd say I'm eager to merge this, it looks quite good and I like the footer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/omarroth/invidious","title":"omarroth/invidious","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/omarroth/invidious"}},"updates":{"snippets":[{"icon":"PERSON","message":"@omarroth in #38: Looks good on desktop, only issue is that when using dark mode the default color is still white, so it looks like this:\r\ndesktop\r\nYou may also want to take a look at mobile, on my iDevice it looks like:\r\niphone.\r\n\r\nI'm also curious why you reversed the order of the preferences, sign out, and notifications icons on the right side. \r\n\r\nOtherwise I'd say I'm eager to merge this, it looks quite good and I like the footer."}],"action":{"name":"View Pull Request","url":"https://github.com/omarroth/invidious/pull/38#issuecomment-407958263"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/omarroth/invidious/pull/38#issuecomment-407958263",
"url": "https://github.com/omarroth/invidious/pull/38#issuecomment-407958263",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [omarroth/invidious] Rework navbar and update README (#38)",
"sections": [
{
"text": "",
"activityTitle": "**Omar Roth**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@omarroth",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"omarroth/invidious\",\n\"issueId\": 38,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"omarroth/invidious\",\n\"pullRequestId\": 38\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/omarroth/invidious/pull/38#issuecomment-407958263"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 360774320\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by FredrikAugust** [comment]
Fixed all of the issues you listed, please let me know if there are more!

**Comment by omarroth** [comment]
Ordering works everywhere except on Chrome, otherwise everything looks good. You might want to clean up your commit history when you have a chance.

**Comment by FredrikAugust** [comment]
It doesn't work on Chrome? Uhhh that's strange. Could you provide a screenshot of the problem?

I'll fix the commit history once I get the green light that it's ready to be merged :)

**Comment by FredrikAugust** [comment]
There's no reason it shouldn't work there, chrome has perfect support for flexbox AFAIK 🤔 Could you check the developer console and style inspector to ensure everything is applied?

If not, I can check it in 45min, currently busy.

**Comment by omarroth** [comment]
Haha, forgot to clear my cache, LGTM :+1:

**Comment by FredrikAugust** [comment]
That's what I feared :)) Cache can be a bit of a headache sometimes. Will push cleaned version in 45min.

**Comment by FredrikAugust** [comment]
There we go, squashed it all into one commit. Ready to merge!

**Pull request merged**
