### PR TITLE
Autofocus search input

### PR DESCRIPTION
**Pull request by jorgesumle**
Because I don't like wasting my time using the mouse to focus on it.

### CODE REVIEW

**Comment by omarroth** [comment]
Would appear to close #277.

As mentioned in the linked issue I would very much prefer for this to be implemented as a shortcut (see #501), as it is on YouTube.

**Comment by jorgesumle** [comment]
A shortcut means one more keystroke, which means more wasted time, and very few people would actually use it because many don't know it exists. With autofocus, you don't have to select the field before you start typing to search a video. As a compromise for those who don't like that, a configuration setting could be implemented.

**Comment by omarroth** [comment]
I don't like this as the default behavior because it's assuming the user's intent. 

The only services I can find that have the search bar autofocused by default are search engines, where it makes much more sense to assume a user wants to search. Even then, only the landing page has the search bar auto-focused.

There's an open issue #449 for having a search page as the default landing page, where it would make sense to have it auto-focused.

> very few people would actually use it because many don't know it exists

GitHub provides a *hint* as a `/` icon, so I could see that as a good option here as well.

**Comment by jorgesumle** [comment]
OK, I understand.

**Pull request closed without merging**
