### PR TITLE
docker: various improvements to Dockerfile

### PR DESCRIPTION
**Pull request by leonklingele**
This includes the following changes:

- Use multi-stage build to run application in an optimized environment, see
  https://docs.docker.com/develop/develop-images/multistage-build/
- Run application on alpine instead of archlinux to further reduce image size
- Build Crystal application with --release for improved runtime performance
- Run application as non-root user for better security, see
  https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
- Only rebuild Docker layers when required

### CODE REVIEW

**Comment by leonklingele** [comment]
Please test this extensively.

Image size of `invidious_invidious` decreased by over 96% (from 1.13GB down to 38.6MB).

**Comment by leonklingele** [comment]
Added missing runtime dependency `imagemagick` (required for CAPTCHAs).

**Comment by omarroth** [comment]
Alpine doesn't appear to include any default fonts, so the CAPTCHA looks like this:
image

It's enough to include `opensans-ttf` or an alternative font:
```diff
diff --git a/docker/Dockerfile b/docker/Dockerfile
index 0c30616..c9fa636 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -17 +17 @@ FROM alpine:latest
-RUN apk add -u imagemagick
+RUN apk add -u imagemagick ttf-opensans
```
Which appears to fix the issue:
image

**Comment by leonklingele** [comment]
Thanks! Updated.

**Comment by omarroth** [comment]
LGTM :+1:

**Comment by leonklingele** [comment]
@omarroth I'd really like to remove the `.git` folder from the Docker build env, see https://github.com/omarroth/invidious/pull/665/files#diff-ebacf6f6ae4ee68078bb16454b23247dR8-R10
This requires to rebuild the Crystal application for every new commit, even if the commit doesn't touch anything related to Crystal.
Do you know of a way to inject variables at build time, similar to Go's `-ldflags "-X main.version=1.2.3"` (https://stackoverflow.com/a/11355611)?

**Comment by leonklingele** [comment]
Ignore what I just said. Rebuilding is required to update the version information shown on the web UI.

**Pull request merged**
