### PR TITLE
docker,travis: fail build on any warning

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by leonklingele** [comment]
CI will fail due to some problems with Crystal 0.31.0 as described in https://github.com/omarroth/invidious/pull/764.
Merging https://github.com/omarroth/invidious/pull/764 and retriggering a CI build should be enough to make it green again.

**Comment by omarroth** [comment]
Unfortunately looks like this and #766 need to be rebased against master in order to pass CI.

They both LGTM though so I don't mind merging as is.

**Comment by leonklingele** [comment]
Rebased.

**Comment by omarroth** [comment]
LGTM :+1:

**Pull request merged**
