### PR TITLE
Add Eepsite

### PR DESCRIPTION
**Pull request by ghbjklhv**
Add Eepsite to README.md

### CODE REVIEW

**Comment by Perflyst** [comment]
This is not an eepsite from omarroth, I would not include it in the readme

**Comment by omarroth** [comment]
I agree it makes sense to keep a list of instances in the README. Maybe it would be good to make the link to alternative instances more prominent?

**Comment by Perflyst** [comment]
Yes, I would prefer a more prominent link to alternative instances.

**Comment by omarroth** [comment]
Added "Invidious Instances" header to README with 6783bf9903aaa810e626864fab73be7ee29d0f0f.

**Pull request closed without merging**
