### PR TITLE
travis: also test Docker build

### PR DESCRIPTION
**Pull request by leonklingele**

### CODE REVIEW

**Comment by leonklingele** [comment]
Looks like we've discovered an issue within Travis. See https://travis-ci.community/t/latest-is-an-invalid-version-of-crystal-even-though-it-is-valid/4663.

Pushed a fix, CI is green now.

**Comment by 0816346191** [comment]
Linlin191

**Comment by leonklingele** [comment]
Now also verifying that the cluster starts up properly and answers via HTTP.

**Comment by omarroth** [comment]
LGTM :+1:

**Pull request merged**
